version: '3.8'

services:
  app:
    image: service-template:latest
    ports:
      - '3000:3000'
    deploy:
      resources:
        reservations:
          cpus: '0.25'
          memory: '128M'
        limits:
          cpus: '0.5'
          memory: '256M'