version: '3.8'

services:
  mongo:
    image: mongo:8.0
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./src/certs/ca.key:/keys/ca.key
      - mongo_data2:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_REPLICA_SET_NAME: rs0
    command:
      [
        'mongod',
        '--replSet',
        'rs0',
        '--bind_ip_all',
        '--keyFile',
        '/keys/ca.key',
        '--dbpath',
        '/data/db',
      ]
    networks:
      - service-net

volumes:
  mongo_data2:

networks:
  service-net:
