version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile.test
    container_name: app-test
    environment:
      NODE_ENV: test
      MONGODB_URI: YOUR_MONGODB_CONNECTION_STRING_HERE # Or configure for your test database
    command: ${TEST_ARGS:-}