version: '3.8'

services:
  service:
    build: .
    container_name: service
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - mongo
    networks:
      - service-net

networks:
  service-net:
