apiVersion: v1
kind: Service
metadata:
  name: service-template-service
spec:
  type: NodePort
  selector:
    app: service-template-service
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
